# title: Thinking AI Research
# description: Investigating LLM training efficiency and chain of thought reasoning.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# theme: jekyll-theme-minimal # Simple, clean, and reliable
google_analytics: G-C5RWE6GL0N # Optional: add your ID here if you want to track views
show_downloads: false

# This ensures every page uses the clean 'default' layout
defaults:
  - scope:
      path: ""
    values:
      layout: default